name: controle_estoque_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utilitários e Estado
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0        # Versão estável e compatível
  rxdart: ^0.27.7

  # Firebase
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_messaging: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versão compatível com Dart 3.0+

flutter:
  uses-material-design: true